import type { Metadata } from 'next'
import './globals.css'
import FinalNavbar from '../components/Navbar/FinalNavbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <FinalNavbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
